# Generated by Django 5.1.4 on 2025-01-11 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_cancelable",
            field=models.BooleanField(default=True),
        ),
    ]
