# Generated by Django 5.1.4 on 2025-01-15 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_is_cancelable"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pendiente"),
                    ("Confirmed", "Confirmado"),
                    ("Dispatched", "Despachado"),
                ],
                default="Pending",
                max_length=10,
            ),
        ),
    ]
