# Generated by Django 5.1.4 on 2025-02-14 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="gender",
            field=models.CharField(
                choices=[
                    ("male", "Masculino"),
                    ("female", "Femenino"),
                    ("unisex", "Unisex"),
                ],
                max_length=10,
            ),
        ),
    ]
